<?php
/**
 * Created by PhpStorm.
 * User: partho
 * Date: 2/12/18
 * Time: 5:34 PM
 */

namespace App\Modules\Misc;


class HardCodedData
{


    public function univInfo(){
        return [
            0   => [
                'univ_abbr'		=> "BOU",
                'univ_name'		=> "Bangladesh Open University",
                'dlt_location'	=> "",
                'in_charge'     => ["Utpal Kumar ghose"],
                'mobile'        => ["01817095283"],
                'email'         => ["partho8181@gmail.com"],
            ],
            1   => [
                'univ_abbr'		=> "BSMMU",
                'univ_name'		=> "Bangabandhu Sheikh Mujib Medical University",
                'dlt_location'	=> "",
                'in_charge'     => ["Md. Mahmudul Kader"],
                'mobile'        => ["01733404505"],
                'email'         => ["mkaderabc@bsmmu.edu.bd"],
            ],
            2   => [
                'univ_abbr'		=> "BSMRAU",
                'univ_name'		=> "Bangabandhu Sheikh Mujibur Rahman Agricultural University",
                'dlt_location'	=> "Central Laboratory Building,1st Floor, Room# 209",
                'in_charge'     => ["Mr. Akram"],
                'mobile'        => ["01743936055"],
                'email'         => ["akramabc@bsmrau.edu.bd"],
            ],
            3   => [
                'univ_abbr'		=> "BSMRSTU",
                'univ_name'		=> "Bangabandhu Sheikh Mujibur Rahman Science and Technology University",
                'dlt_location'	=> "Academic Building,4th Floor, Room#501 (ex Hall Room)",
                'in_charge'     => ["Ariful Islam", "Akkas Ali"],
                'mobile'        => ["01717385464", "01731336006"],
                'email'         => ["shakil_ai_bdabc@yahoo.com", "akkas.buetabc@gmail.com"],
            ],
            4   => [
                'univ_abbr'		=> "BAU",
                'univ_name'		=> "Bangladesh Agricultural University",
                'dlt_location'	=> "Library Building,2nd Floor,Room# virtual class room",
                'in_charge'     => ["Mr. Shohel", "Ali Ashraf"],
                'mobile'        => ["01616625873", "01718353743"],
                'email'         => ["sohelcsmabc@bau.edu.bd", null],
            ],
            5   => [
                'univ_abbr'		=> "BUTex",
                'univ_name'		=> "Bangladesh University of Textiles",
                'dlt_location'	=> "Academic Bhaban,3rd Floor,Room#402",
                'in_charge'     => ["Jahirul Haque","A.N.M Bazlur Rashid"],
                'mobile'        => ["01722775141","01712617264"],
                'email'         => [null,"anm.bazlur.rashidabc@gmail.com"],
            ],
            6   => [
                'univ_abbr'		=> "BUET",
                'univ_name'		=> "Bangladesh University of Engineering and Technology",
                'dlt_location'	=> "ECE Building,7th Floor,Room#705",
                'in_charge'     => ["Mr. Sazzad","Mr. NASIR","Mr. Mahbub Kabir",],
                'mobile'        => ["01739884023","01554338937","01740572601",],
                'email'         => ["sazzadwahidabc@iict.buet.ac.bd","nasirabc@iict.buet.ac.bd",null,],
            ],
            7   => [
                'univ_abbr'		=> "BUP",
                'univ_name'		=> "Bangladesh University of Professional",
                'dlt_location'	=> "Academic Building,2nd Floor, Room#304",
                'in_charge'     => ["Mazharul Islam Tuhin","Mr. Hasan","Imran"],
                'mobile'        => ["01673223736","01769021599","01769021599"],
                'email'         => ["tuhinbd1abc@gmail.com", null, null],
            ],
            8   => [
                'univ_abbr'		=> "BUP",
                'univ_name'		=> "Bangladesh University of Professional",
                'dlt_location'	=> "Academic Building,2nd Floor, Room#304",
                'in_charge'     => ["Mazharul Islam Tuhin","Mr. Hasan","Imran"],
                'mobile'        => ["01673223736","01769021599","01769021599"],
                'email'         => ["tuhinbd1abc@gmail.com", null, null],
            ],
            9   => [
                'univ_abbr'		=> "BRUR",
                'univ_name'		=> "Begum Rokeya University, Rangpur",
                'dlt_location'	=> "Academic Building-2,2nd Floor, CSE Dept,Room# 301",
                'in_charge'     => ["Md. Abul Kalam Azad", "Mr. Milon"],
                'mobile'        => ["01710504692", "01714551000"],
                'email'         => ["akazadabc@brur.ac.bd", "melonbrurabc@gmail.com"],
            ],
            10  => [
                'univ_abbr'		=> "CUET",
                'univ_name'		=> "Chittagong University of Engineering and Technology",
                'dlt_location'	=> "Engineering Building,2nd Floor, Room# Virtual class room",
                'in_charge'     => ["Md. Tawhidur Rahman", "Md Abdulla Al Mamun", "Md. Moyeen Uddin", "Prof. Dr.Kaushik De", "Sagar Talukder"],
                'mobile'        => ["01931887866", "01912214591", "01815340062", "01914745508", "01814327039"],
                'email'         => ["towhidcuetabc@gmail.com", "lmnmamunabc@gmail.com", "moyeencceabc@gmail.com", "debkaushik99abc@gmail.com", null],
            ],
            11  => [
                'univ_abbr'		=> "CVASU",
                'univ_name'		=> "Chittagong Veterinary and Animal Sciences University",
                'dlt_location'	=> "Old Academic Bhaban,3rd Floor,Room# Classs Room 02",
                'in_charge'     => ["Selim Morshed", "Prof. Md. Abdul Halim", "Mamun Shikder", "Nasim Ahmed"],
                'mobile'        => ["01715315660", "01554324509", "01738203209", "01991953330"],
                'email'         => [null, null, null, "nasimciscoabc@gmail.com"],
            ],
            12  => [
                'univ_abbr'		=> "CU",
                'univ_name'		=> "Comilla University",
                'dlt_location'	=> "Administrative Building,Ground Floor, Room #111",
                'in_charge'     => [null],
                'mobile'        => [null],
                'email'         => [null],
            ],
            13  => [
                'univ_abbr'		=> "DUET",
                'univ_name'		=> "Dhaka University of Engineering and Technology",
                'dlt_location'	=> "Old Academic Building,2nd Floor, Room#330",
                'in_charge'     => ["Prof. Dr. Obaidur Rahman", "Mr.Nazrul Islam"],
                'mobile'        => ["01930706863", "01721081878"],
                'email'         => ["orahmanabc@duet.ac.bd", null],
            ],
            14  => [
                'univ_abbr'		=> "HSTU",
                'univ_name'		=> "Hajee Mohammad Danesh Science & Technology University",
                'dlt_location'	=> "Dr. M A Wazed Bhaban,1st Floor, Room# 238",
                'in_charge'     => ["Mr. Ahmadul Hoque", "Mr. Tanvir", "Saikat"],
                'mobile'        => ["01737349069", "01727319332", "01717676689"],
                'email'         => ["ahmadul.itcellabc@hstu.ac.bd", "tanvir.rahmanabc@gmail.com", "saikat02eeeabc@yahoo.com"],
            ],
            15  => [
                'univ_abbr'		=> "IU",
                'univ_name'		=> "Islamic University, Kustia",
                'dlt_location'	=> "Science Building/Folito Biggan Anushadh,1st Floor,Room# 206/ virtual class room",
                'in_charge'     => ["Dr. Poresh"],
                'mobile'        => ["01727300119"],
                'email'         => ["pcbabc@ice.iu.ac.bd"],
            ],
            16  => [
                'univ_abbr'		=> "JnU",
                'univ_name'		=> "Jagannath University",
                'dlt_location'	=> "New Building(Notun Bhaban),CSE Dept, Cyber Center,5th Floor, Room#601(Ka)",
                'in_charge'     => ["Uzzal Kumar Achargy","Mahbub Alam Saikat"],
                'mobile'        => ["01625099037","01913054120"],
                'email'         => ["uzzalabc@cse.jnu.ac.bd","shoikot.bd26abc@gmail.com"],
            ],
            17  => [
                'univ_abbr'		=> "JU",
                'univ_name'		=> "Jahangirnagar University",
                'dlt_location'	=> "Physics Building,2nd Floor, Room#  Last Room of West Side",
                'in_charge'     => ["Mr. Naymul Hasan", "Mr. S.M Khiroul Bashar"],
                'mobile'        => ["01819141780", "01749416824"],
                'email'         => ["naimulh_pavel_eeeabc@yahoo.com", "bashar.juabc@juniv.edu"],
            ],
            18  => [
                'univ_abbr'		=> "JKKNIU",
                'univ_name'		=> "Jatiya Kabi Kazi Nazrul Islam University",
                'dlt_location'	=> "Administrative Building,2nd Floor,Room# Virtual Class Room (ex Seminar Room)",
                'in_charge'     => ["Mustaq Ahammad", "Md. Samiul"],
                'mobile'        => ["01710263060", "01712284283"],
                'email'         => ["mustak_jkkniuabc@yahoo.com", "samiul1992abc@gmail.com"],
            ],
            19  => [
                'univ_abbr'		=> "JUST",
                'univ_name'		=> "Jessore University of Science & Technology",
                'dlt_location'	=> "Academic Bhaban,1st Floor, Room#236",
                'in_charge'     => ["Md. Rakibul Hassan", "Shamim Rahman"],
                'mobile'        => ["01923836876", "01689480780"],
                'email'         => ["just.ictcell.internetabc@gmail.com", "rossel0203113abc@gmail.com"],
            ],
            20  => [
                'univ_abbr'		=> "KU",
                'univ_name'		=> "Khulna University",
                'dlt_location'	=> "Shottendro Nath Academic Bhaban-1Ground Floor, Room# ECE1103",
                'in_charge'     => ["Pritish Ray", "Dr. M Moniruzzaman"],
                'mobile'        => ["01961973556", "01914066284"],
                'email'         => ["pritish.ray1976abc@gmail.com", null],
            ],
            21  => [
                'univ_abbr'		=> "KUET",
                'univ_name'		=> "Khulna University of Engineering &Technology",
                'dlt_location'	=> "Science Building,Ground Floor, Room#Distance Learning Theater (ex Gallery Room)",
                'in_charge'     => ["Prodip Kumar Das", "Mihir Lal"],
                'mobile'        => ["01914134458", "01912516628"],
                'email'         => ["prodipkuetabc@gmail.com", "mehirabc@kuet.ac.bd"],
            ],
            22  => [
                'univ_abbr'		=> "MBSTU",
                'univ_name'		=> "Mawlana Bhashani Science and Technology University",
                'dlt_location'	=> "Academic Bhaban 1,1st Floor, CSE Dept.Room# 212",
                'in_charge'     => ["Mr. Hasnat", "Sazzad", "Mizan", "Amzad Hossain", "Md. Atiqul Haque"],
                'mobile'        => ["01925305555", "01787064807", "01944654454", "01819538414", "01717055517", ],
                'email'         => ["shohug2003abc@gmail.com", "sajad302abc@yahoo.com", null, "amzadksmlabc@gmail.com", "suzan.duet059abc@gmail.com", ],
            ],
            23  => [
                'univ_abbr'		=> "NU",
                'univ_name'		=> "National University",
                'dlt_location'	=> "New Academic Building,Floor# 12th, Room# Virtual Class Room",
                'in_charge'     => ["Mr. Zillur Rahman", "Mr. Haydar"],
                'mobile'        => ["01716380022", "01712993175"],
                'email'         => ["zs_rahmanabc@yahoo.com", null],
            ],
            24  => [
                'univ_abbr'		=> "NSTU",
                'univ_name'		=> "Noakhali Science and Technology University",
                'dlt_location'	=> "Academic Bhaban 2,1st Floor, Room# Virtual Class Room or VC Room",
                'in_charge'     => ["Abdullah Hil Faruk", "Nuruzzaman Bhuiyan", "Humayun Kabir"],
                'mobile'        => ["01716615953", "01612032781", "01814405238"],
                'email'         => ["mahfarukabc@gmail.com", "mdnuruzzaman2001abc@yahoo.com", "hkabir269abc@gmail.com"],
            ],
            25  => [
                'univ_abbr'		=> "PUST",
                'univ_name'		=> "Pabna University of Science & Technology",
                'dlt_location'	=> "Library Building,2nd Floor,Room# virtual class room",
                'in_charge'     => ["Sazzad sir"],
                'mobile'        => ["01753622822"],
                'email'         => ["sazzadiceabc@gmail.com"],
            ],
            26  => [
                'univ_abbr'		=> "PSTU",
                'univ_name'		=> "Patuakhali Science and Technology University",
                'dlt_location'	=> "CSE-BBA Building 1,3rd Floor, Room#402",
                'in_charge'     => ["Shahidul Islam", "Chinmoy Kumar"],
                'mobile'        => ["01713605804", "01922361666"],
                'email'         => ["msimymabc@gmail.com", "chinmay.cseabc@pstu.ac.bd"],
            ],
            27  => [
                'univ_abbr'		=> "RUET",
                'univ_name'		=> "Rajshahi University of Engineering & Technology",
                'dlt_location'	=> "CSE Building,1st Floor,Room# Virtual Class Room",
                'in_charge'     => ["Bimolendu Sarker", "Prof. Dr. Md. Shahiduzzaman", "Dr. Ali Hossain"],
                'mobile'        => ["01713228505", "01713228537", "01959600498"],
                'email'         => ["bimolenduabc@ruet.ac.bd", "szaman22abc@yahoo.com", null],
            ],
            28  => [
                'univ_abbr'		=> "SBAU",
                'univ_name'		=> "Sher-e-Bangla Agricultural University",
                'dlt_location'	=> "Krishi Anushadh Bhaban,1st Floor, Room# Virtual Class Room",
                'in_charge'     => ["Md. Rayhan Uddin"],
                'mobile'        => ["01911552528"],
                'email'         => ["md.rayhanabc@yahoo.com"],
            ],
            29  => [
                'univ_abbr'		=> "SAU",
                'univ_name'		=> "Sylhet Agricultural University",
                'dlt_location'	=> "Krishi Anushadh Bhaban,1st Floor, Room# 206",
                'in_charge'     => ["Mitryunjoy Biswas", "Dr. Rafiqul Islam", "Himangsu", "Pronozit Kumar"],
                'mobile'        => ["01711240580", "01742824654", "01610005797", "01911926710"],
                'email'         => ["biswasbariabc@yahoo.com", "dr.rafiqsauabc@gmail.com", "himangshuabc@sau.ac.bd", "pkdabc@sau.ac.bd"],
            ],
            30  => [
                'univ_abbr'		=> "SUST",
                'univ_name'		=> "Shahjalal University of Science and Technology",
                'dlt_location'	=> "IICT Building,1st Floor (East Side),Room# VC room",
                'in_charge'     => ["Mr. Khairul", "Sayed Ahmed"],
                'mobile'        => ["01711148424", "01711345113"],
                'email'         => ["khayrulabc@sust.edu", "syedabc@sust.edu"],
            ],
            31  => [
                'univ_abbr'		=> "BU",
                'univ_name'		=> "University of Barisal",
                'dlt_location'	=> "Administrative Building,4th Floor,Room# Virtual Class Room",
                'in_charge'     => ["Rahat", "Kamrul", "Asif"],
                'mobile'        => ["01552405815", "01734258990", "01717557997"],
                'email'         => ["rhfaisalabc@gmail.com", "kamrulhasan.bu.ictabc@gmail.com", null],
            ],
            32  => [
                'univ_abbr'		=> "CU",
                'univ_name'		=> "University of Chittagong",
                'dlt_location'	=> "ICT Building,2nd Floor, Room#308",
                'in_charge'     => ["Mohammad Forkan", "Mojnu", "Muhammad Anwarul Azim", "Prof. Sahadat Hossain"],
                'mobile'        => ["01818583409", "01911721974", "01799634272", "01819336660"],
                'email'         => ["forkan.cuabc@gmail.com", "mojnucuabc@yahoo.com", "azimabc@cu.ac.bd", null],
            ],
            33  => [
                'univ_abbr'		=> "DU",
                'univ_name'		=> "University of Dhaka",
                'dlt_location'	=> "DLT-1 Register Building,Ground Floor, Abdul Matin Virtual Class Room(Next to VC Office)
					DLT-2 CARASS Building, (in the middle of TSC and Atomic Energy Building)2nd Floor, Room# N/A ( Right side of Stair)",
                'in_charge'     => ["Imam Hasan Raza","Tomal Adhikari"],
                'mobile'        => ["01730796929","01676325072"],
                'email'         => ["hasanabc@du.ac.bd","tamalabc@cse.du.ac.bd"],
            ],
            34  => [
                'univ_abbr'		=> "RU",
                'univ_name'		=> "University of Rajshahi",
                'dlt_location'	=> "4th Science Building, Room#205",
                'in_charge'     => ["Khademul Islam", "Rahel Mahfuz"],
                'mobile'        => ["01727786600", "01750071045"],
                'email'         => ["khademul.cseabc@ru.ac.bd", "rahelabc@ru.ac.bd"],
            ]
        ];
    }
}